let myDate = new Date()
// console.log( myDate.toLocaleTimeString())
// console.log(myDate.getTimezoneOffset())
// console.log(myDate.getUTCDate())
// console.log(myDate.toLocaleString())
// console.log(myDate.toDateString()) 
console.log(typeof myDate)
// const newDate = new Date(2024,0,4)
// console.log(newDate.toDateString())
const newDate= new Date ("4/02/2024")
console.log(newDate.toLocaleString())
console.log(newDate.toDateString())
//  for polling in quiz
let myTimeStamp = Date.now()
console.log(myTimeStamp)
console.log(newDate.getTime())